[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_restarter = "7CsExyLgAeZibmwb1r3jh2HrmkMEdqVi2knL52gofTPD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test]
skip-lint = true

[test.validator]
url = "http://127.0.0.1:8898"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
